// <auto-generated />
using System;
using InternshipLogbook.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipLogbook.API.Migrations
{
    [DbContext(typeof(InternshipLogbookDbContext))]
    [Migration("20260216163814_AddSecurityStamp")]
    partial class AddSecurityStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipLogbook.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.DailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfActivity")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsPracticed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TimeFrame")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DailyAct__3214EC071D55DE6E");

                    b.HasIndex("StudentId");

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.InternshipEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CareerAnalysis")
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationClients")
                        .HasColumnType("int");

                    b.Property<int?>("CommunicationTeam")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyKnowledge")
                        .HasColumnType("int");

                    b.Property<int?>("DataRecording")
                        .HasColumnType("int");

                    b.Property<int?>("Design")
                        .HasColumnType("int");

                    b.Property<int?>("Documentation")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricalAssembly")
                        .HasColumnType("int");

                    b.Property<int?>("EthicalConduct")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GraphicPlans")
                        .HasColumnType("int");

                    b.Property<int?>("ManualAssembly")
                        .HasColumnType("int");

                    b.Property<int?>("Measurements")
                        .HasColumnType("int");

                    b.Property<int?>("OrgCulture")
                        .HasColumnType("int");

                    b.Property<int?>("Reflection")
                        .HasColumnType("int");

                    b.Property<int?>("SafetyFeatures")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskSequencing")
                        .HasColumnType("int");

                    b.Property<int?>("Techniques")
                        .HasColumnType("int");

                    b.Property<int?>("Testing")
                        .HasColumnType("int");

                    b.Property<int?>("TheoreticalKnowledge")
                        .HasColumnType("int");

                    b.Property<int?>("ToolsUsage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("InternshipEvaluations");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EvaluationCommunication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluationLearning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluationQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HostTutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternshipDirector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternshipPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudyProgrammeId")
                        .HasColumnType("int");

                    b.Property<int?>("SuggestedGrade")
                        .HasColumnType("int");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Students");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudyProgrammeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.StudyProgramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("StudyProgrammes");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.DailyActivity", b =>
                {
                    b.HasOne("InternshipLogbook.API.Models.Student", "Student")
                        .WithMany("DailyActivities")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_DailyActivities_Students");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.InternshipEvaluation", b =>
                {
                    b.HasOne("InternshipLogbook.API.Models.Student", "Student")
                        .WithOne("InternshipEvaluation")
                        .HasForeignKey("InternshipLogbook.API.Models.InternshipEvaluation", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Student", b =>
                {
                    b.HasOne("InternshipLogbook.API.Models.Company", "Company")
                        .WithMany("Students")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Students_Companies");

                    b.HasOne("InternshipLogbook.API.Models.StudyProgramme", "StudyProgramme")
                        .WithMany("Students")
                        .HasForeignKey("StudyProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Students_StudyProgrammes");

                    b.Navigation("Company");

                    b.Navigation("StudyProgramme");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.StudyProgramme", b =>
                {
                    b.HasOne("InternshipLogbook.API.Models.Faculty", "Faculty")
                        .WithMany("StudyProgrammes")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudyProgrammes_Faculties");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.User", b =>
                {
                    b.HasOne("InternshipLogbook.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Company", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Faculty", b =>
                {
                    b.Navigation("StudyProgrammes");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.Student", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("InternshipEvaluation");
                });

            modelBuilder.Entity("InternshipLogbook.API.Models.StudyProgramme", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
